---
apiVersion: "v1"
data:
  hubot-irc-server: "irc.freenode.net"
  hubot-irc-password: ""
  hubot-irc-unflood: "false"
  hubot-grafana-host: ""
  hubot-jenkins-url: "http://jenkins"
  hubot-irc-usessl: "1"
  hubot-irc-debug: "true"
  hubot-irc-nickserv-password: ""
  hubot-grafana-api-key: ""
  hubot-irc-rooms: "#fabric8_default,#random"
  hubot-irc-nick: "fabric8"
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.hubot-irc/summary: "[Hubot](http://hubot.github.com) IRC chat bot"
    description: "Chat bot app using [Hubot](https://hubot.github.com/) and an IRC\
      \ server to communicate with fabric8."
    fabric8.hubot-irc/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/hubot-irc/src/main/fabric8/icon.png"
    fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n \
      \   \"HUBOT_IRC_USESSL\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"Use SSL\",\n      \"default\" : \"1\"\n    },\n    \"HUBOT_GRAFANA_API_KEY\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"API key for a\
      \ particular user\"\n    },\n    \"HUBOT_IRC_NICK\" : {\n      \"type\" : \"\
      string\",\n      \"description\" : \"The name that hubot should joing the room\
      \ as\",\n      \"default\" : \"fabric8\"\n    },\n    \"HUBOT_IRC_DEBUG\" :\
      \ {\n      \"type\" : \"string\",\n      \"description\" : \"Enables debug logging\"\
      ,\n      \"default\" : \"true\"\n    },\n    \"HUBOT_IRC_ROOMS\" : {\n     \
      \ \"type\" : \"string\",\n      \"description\" : \"List of rooms to join including\
      \ '#' prefix\",\n      \"default\" : \"#fabric8_default,#random\"\n    },\n\
      \    \"HUBOT_GRAFANA_HOST\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'\"\n\
      \    },\n    \"HUBOT_IRC_UNFLOOD\" : {\n      \"type\" : \"string\",\n     \
      \ \"description\" : \"Unflood\",\n      \"default\" : \"false\"\n    },\n  \
      \  \"HUBOT_JENKINS_URL\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"The URL for the Jenkins CI server\",\n      \"default\" : \"http://jenkins\"\
      \n    },\n    \"HUBOT_IRC_SERVER\" : {\n      \"type\" : \"string\",\n     \
      \ \"description\" : \"The IRC server\",\n      \"default\" : \"irc.freenode.net\"\
      \n    },\n    \"HUBOT_IRC_NICKSERV_PASSWORD\" : {\n      \"type\" : \"string\"\
      ,\n      \"description\" : \"IRC nick password\"\n    },\n    \"HUBOT_IRC_PASSWORD\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"IRC password\"\
      \n    }\n  }\n}"
  labels: {}
  name: "hubot-irc"
