---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
    project: "${project.artifactId}"
  annotations:
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/gogs/src/main/fabric8/icon.png"
  name: "gogs"
