---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/app-menu: development
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/nexus/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
    expose: "true"
  name: "nexus"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8081
  selector:
    project: "nexus"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
