---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/chaos-monkey/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "chaos-monkey"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: "CHAOS_MONKEY_INCLUDES"
          valueFrom:
            configMapKeyRef:
              key: "chaos-monkey-includes"
              name: "chaos-monkey"
        - name: "CHAOS_MONKEY_EXCLUDES"
          valueFrom:
            configMapKeyRef:
              key: "chaos-monkey-excludes"
              name: "chaos-monkey"
        - name: "CHAOS_MONKEY_ROOM"
          valueFrom:
            configMapKeyRef:
              key: "chaos-monkey-room"
              name: "chaos-monkey"
        - name: "CHAOS_MONKEY_KILL_FREQUENCY_SECONDS"
          valueFrom:
            configMapKeyRef:
              key: "chaos-monkey-kill-frequency-seconds"
              name: "chaos-monkey"
        - name: "KUBERNETES_MASTER"
          value: "https://kubernetes.default.svc"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/chaos-monkey:${project.version}"
        name: "chaos-monkey"
        ports:
        - containerPort: 8778
          name: "jolokia"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      serviceAccountName: "chaos-monkey"
