---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/gerrit/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "gerrit"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      annotations:
        fabric8.io/secret-ssh-key: "gerrit-admin-ssh"
        fabric8.io/secret-ssh-public-key: "gerrit-users-ssh-keys[id-jenkins-rsa.pub,id-sonar-rsa.pub]"
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: "GERRIT_PUBLIC_KEYS_PATH"
          value: "/home/gerrit/ssh-keys"
        - name: "GIT_SERVER_PASSWORD"
          value: "RedHat$1"
        - name: "GERRIT_ADMIN_FULLNAME"
          value: "Administrator"
        - name: "GERRIT_ACCOUNTS"
          value: "jenkins,jenkins,jenkins@fabric8.io,secret,Non-Interactive Users:Administrators;sonar,sonar,sonar@fabric8.io,secret,Non-Interactive\
            \ Users"
        - name: "GERRIT_ADMIN_USER"
          valueFrom:
            configMapKeyRef:
              key: "gerrit-admin-user"
              name: "gerrit"
        - name: "GIT_SERVER_IP"
          value: "gogs.default.svc.cluster.local"
        - name: "GERRIT_ADMIN_PRIVATE_KEY"
          value: "/root/.ssh/id_rsa"
        - name: "GERRIT_REPO_DESCRIPTION"
          valueFrom:
            configMapKeyRef:
              key: "gerrit-repo-description"
              name: "gerrit"
        - name: "GERRIT_SSH_PATH"
          value: "/root/.ssh"
        - name: "GERRIT_ADMIN_EMAIL"
          value: "admin@fabric8.io"
        - name: "GERRIT_GIT_REMOTEPATH"
          value: "ssh://admin@localhost:29418/All-Projects"
        - name: "GIT_SERVER_PROJ_ROOT"
          value: "gogsadmin"
        - name: "GERRIT_ADMIN_PWD"
          valueFrom:
            configMapKeyRef:
              key: "gerrit-admin-pwd"
              name: "gerrit"
        - name: "GERRIT_GIT_PROJECT_CONFIG"
          value: "/home/gerrit/configs/project.config"
        - name: "GIT_SERVER_PORT"
          value: "80"
        - name: "GERRIT_INITIAL_COMMIT"
          valueFrom:
            configMapKeyRef:
              key: "gerrit-initial-commit"
              name: "gerrit"
        - name: "GERRIT_USER_PUBLIC_KEY_SUFFIX"
          value: "-rsa.pub"
        - name: "GIT_SERVER_USER"
          value: "gogsadmin"
        - name: "GERRIT_GIT_LOCALPATH"
          value: "/home/gerrit/git"
        - name: "GERRIT_USER_PUBLIC_KEY_PREFIX"
          value: "id-"
        - name: "AUTH_TYPE"
          value: "DEVELOPMENT_BECOME_ANY_ACCOUNT"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/gerrit:${project.version}"
        imagePullPolicy: "IfNotPresent"
        name: "gerrit"
        ports:
        - containerPort: 8080
          name: "http"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: "/root/.ssh"
          name: "gerrit-admin-ssh-key"
          readOnly: false
        - mountPath: "/home/gerrit/ssh-keys"
          name: "gerrit-users-ssh-keys"
          readOnly: false
      serviceAccountName: "gerrit"
      volumes:
      - name: "gerrit-admin-ssh-key"
        secret:
          secretName: "gerrit-admin-ssh"
      - name: "gerrit-users-ssh-keys"
        secret:
          secretName: "gerrit-users-ssh-keys"
