---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/gerrit/src/main/fabric8/icon.png"
  name: "gerrit"
secrets:
- name: "gerrit-admin-ssh"
- name: "gerrit-users-ssh-keys"
